name: "Test - action"

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js LTS
      uses: actions/setup-node@v1
      with:
        node-version: '20.x'
    - uses: bahmutov/npm-install@v1
      with:
        install-command: yarn --immutable
    - name: Code quality
      run: make lint format
    - name: Unit Tests
      run: make test
      env:
        CI: true
