name: "Test - action"

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js LTS
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Code quality
      run: make lint format
    - name: Unit Tests
      run: make test
      env:
        CI: true
